---
title: "PreProcessing"
author: "Bruno Carlin"
date: "29/06/2018"
output:
  html_document:
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---

# Importing the libraries

## R
```{r}
library(reticulate)
```


## Python
```{python pYTHON}

import pandas as py
import matplotlib as plt
import pandas as pd

``` 

# Importing the dataset

## Python

Requires the dataset to be in the same folder
```{python}
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3]
```

## R
```{r, echo=FALSE, background= T}
X <- py$X
Y <- py$y
dataset = py$dataset
```



# Taking care of missing data

## Python
```{python Python method }
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN',strategy = 'mean',axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)
```

## R
```{r R Method}

dataset$Age <-
  ifelse(is.na(dataset$Age),
         ave(
           dataset$Age,
           FUN = function(x)
             mean(x, na.rm = T)
         ),
         dataset$Age)
         
dataset$Age <- ifelse(is.na(dataset$Age),ave(dataset$Age, FUN = function(x) mean(x, na.rm = T)),dataset$Age)

NA2mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
dataset<- replace(dataset, TRUE, lapply(dataset, NA2mean))
```




